version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02_data.sql
      - ./queries:/queries
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: