spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: storing-service
          uri: ${STORING_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/works/**
        - id: analysis-service
          uri: ${ANALYSIS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/works/*/reports

server:
  port: ${SERVER_PORT:8080}
