spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tigerbank
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

logging:
  level:
    ru.bauman.tigerbank: DEBUG
    org.springframework.jdbc: DEBUG