server:
  port: 9092

spring:
  application:
    name: telemetry-service
  datasource:
    url: jdbc:postgresql://localhost:5432/satellite_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: telemetry-group

grpc:
  server:
    port: 9091

logging:
  level:
    ru.bauman.telemetry: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
