spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false

logging:
  level:
    root: WARN
    ru.bauman.seminar: DEBUG