spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME:satellite_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

grpc:
  client:
    telemetry-service:
      address: static://telemetry-service:9091
      negotiationType: plaintext

logging:
  level:
    ru.bauman.seminar: INFO
    ru.bauman.seminar.telemetry: INFO
    # org.hibernate.SQL: DEBUG
